package org.example.projectfinder.scraper.website;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.example.projectfinder.model.dto.ProjectDto;
import org.example.projectfinder.scraper.ScraperInterface;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jspecify.annotations.NonNull;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

/**
 * Scrapes the Cinode website document and parses the data to a list of
 * {@link ProjectDto}.
 * <p>
 * Retrieves a pre-rendered page generated by Scully for Angular apps
 * and extracts the job/project data using Jsoup and Jackson. All jobs/projects
 * are present in the same Scully block, with no pagination logic needed.
 */
@Slf4j
@Component
public class CinodeScraper implements ScraperInterface {

    // Name tag to be stored in each ProjectDto
    private static final String SITE_NAME = "Cinode";

    // Doc URL
    private static final String LISTING_URL = "https://cinode.market/requests";

    // Used for finding the job-node inside the Scully response, not used for API call
    private static final String REQUEST_FILTER_PATH = "/api/requests/filter";

    private static final ObjectMapper MAPPER = new ObjectMapper();

    /**
     * Fetches the website document and calls helper methods to
     * extract JSON from a Scully block and then map the data to
     * {@link ProjectDto}.
     *
     * @return list of scraped projects mapped to {@link ProjectDto}
     */
    @Override
    public List<ProjectDto> scrape() {
        List<ProjectDto> scrapedProjects = new ArrayList<>();

        try {
            Document doc = Jsoup.connect(LISTING_URL)
                    .userAgent("Mozilla/5.0")
                    .timeout(60_000)
                    .get();

            String decodedJson = extractAndDecodeScullyBlock(doc);

            if (decodedJson == null || decodedJson.isBlank()) {
                log.warn("[Cinode] No Scully block found");
                return scrapedProjects;
            }

            scrapedProjects.addAll(parseProjects(decodedJson));

        } catch (Exception e) {
            log.error("[Cinode] Scraping failed", e);
        }

        log.info("[Cinode] Jobs found: {}", scrapedProjects.size());
        return scrapedProjects;
    }

    /**
     * Extracts the part of the doc containing job listings.
     * @param doc containing data loaded and encoded by Scully
     * @return part of document containing job listings as decoded JSON
     */
    private String extractAndDecodeScullyBlock(Document doc) {

        Element script = doc.selectFirst("#ScullyIO-transfer-state");
        if (script == null) {
            log.warn("[Cinode] Scully script tag not found");
            return null;
        }

        String scriptHtml = script.html();

        // Extract encoded Scully block (state)
        String startMarker = "/** ___SCULLY_STATE_START___ */";
        String endMarker = "/** ___SCULLY_STATE_END___ */";

        int start = scriptHtml.indexOf(startMarker);
        int end = scriptHtml.indexOf(endMarker);

        if (start == -1 || end == -1) {
            log.warn("[Cinode] Scully markers not found");
            return null;
        }

        String encoded = scriptHtml.substring(start + startMarker.length(), end);

        return decodeScully(encoded);
    }

    /**
     * Reformats Scully data to make it parseable for Jackson.
     * @param encoded Scully block containing job listings
     * @return decoded data as JSON
     */
    private static @NonNull String decodeScully(String encoded) {
        Map<String, String> replacements = Map.of(
                "_~b~", "`",
                "_~q~", "'",
                "_~o~", "$",
                "_~s~", "/",
                "_~l~", "<",
                "_~g~", ">"
        );

        String decoded = encoded
                .replace("_~d~", "\\\"");

        for (Map.Entry<String, String> entry : replacements.entrySet()) {
            decoded = decoded.replace(entry.getKey(), entry.getValue());
        }

        decoded = decoded
                .replace("\n", "\\n")
                .replace("\t", "\\t")
                .replace("\r", "\\r");
        return decoded;
    }

    /**
     * Parses the decoded Scully JSON block and extracts all jobs as DTOs.
     * Searches for a key containing class variable REQUEST_FILTER_PATH and maps
     * every entry in the JSON array to a {@link ProjectDto}.</p>
     *
     * @param decodedJson decoded Scully block as JSON
     * @return list of parsed projects as DTOs
     * @throws IOException if parsing of JSON fails
     */
    private List<ProjectDto> parseProjects(String decodedJson) throws IOException {

        List<ProjectDto> projects = new ArrayList<>();

        // Tree representation of entire decoded Scully block
        JsonNode root = MAPPER.readTree(decodedJson);

        for (Iterator<String> it = root.fieldNames(); it.hasNext();) {
            String key = it.next();

            // The key for the JSON array containing jobs includes this String
            if (key.contains(REQUEST_FILTER_PATH)) {
                JsonNode jobsArray = root.get(key);

                if (jobsArray != null && jobsArray.isArray()) {
                    for (JsonNode job : jobsArray) {
                        ProjectDto dto = mapJob(job);
                        if (dto != null) {
                            projects.add(dto);
                        }
                    }
                }
            }
        }

        return projects;
    }

    /**
     * Maps a JSON node to a {@link ProjectDto} using helper methods.
     * @param job JsonNode containing one job
     * @return fully parsed job as a ProjectDto
     */
    private ProjectDto mapJob(JsonNode job) {

        try {
            ProjectDto dto = new ProjectDto();

            dto.setDescription(getText(job, "title"));
            dto.setStartDate(parseDate(getText(job, "startDate")));
            dto.setEndDate(parseDate(getText(job, "endDate")));
            dto.setExpiration(parseDate(getText(job, "deadline")));
            dto.setUrl(LISTING_URL + "/" + getText(job, "id"));
            dto.setLocation(extractLocation(job));
            dto.setOrigin(SITE_NAME);

            return dto;

        } catch (Exception e) {
            log.warn("[Cinode] Failed to map job: {}", job, e);
            return null;
        }
    }

    /**
     * Extracts the location from nested JSON node.
     * @param job format example: "location":{"city":"Växjö","country":"Sweden","displayName":"Växjö"}
     * @return either displayName, city, or country, depending on which field is available
     */
    private String extractLocation(JsonNode job) {
        JsonNode location = job.get("location");
        if (location == null || location.isNull()) {
            return null;
        }

        // First option is to put displayName as location
        String display = getText(location, "displayName");
        if (display != null && !display.isBlank()) {
            return display;
        }

        // Second option is to put city as location
        String city = getText(location, "city");
        if (city != null && !city.isBlank()) {
            return city;
        }

        // Last option is to put country as location
        String country = getText(location, "country");
        if (country != null && !country.isBlank()) {
            return country;
        }

        return null;
    }

    /**
     * Extracts the String value from any JSON node.
     */
    private String getText(JsonNode node, String field) {
        JsonNode v = node.get(field);
        return v != null && !v.isNull() ? v.asText() : null;
    }

    /**
     * Extracts the date as the first 10 characters of an ISO timestamp string.
     */
    private LocalDate parseDate(String date) {
        if (date == null || date.isBlank()) return null;
        return LocalDate.parse(date.substring(0, 10)); // Handles any ISO strings
    }
}
